version: 1.0
expUUID: 52129324-81d7-4e05-83c2-fc39dd456984
name: COPY
author: vulhub
tags:
- d:easy
- flask
- python
desc: 本实验移植了来自Vulhub的Flask SSTI漏洞环境，作为靶场管理系统功能测试。
components:
- flask:
    types: KUBERNETES
    config: web-deployment.yaml
- flask_service:
    types: KUBERNETES
    config: web-service.yaml
attachments: []
solution: ''
